common: &common
  adapter:  postgresql
  encoding: unicode
  username: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *common
  database: workforce_dev # OR your database name
dev_it:
  <<: *common
  database: workforce_dev # OR your database name
staging:
  <<: *common
  database: workforce_dev # OR your database name
production:
  <<: *common
  database: workforce_production # OR your database name
test:
  <<: *common
  database: workforce_test # OR your database name
  min_messages: WARNING